################################################################################
# General metadata
################################################################################
# Specified in the same way as normal Python package metadata, see
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
[project]
# These fields are required:
name = "avogadro-demo-pypkg"  # Must begin with `avogadro-` and may not include underscores
version = "6.0.2"
description = "An example Python package plugin for Avogadro 2 to demonstrate the revamped plugin API in v2.0 onwards"
authors = [
    { name = "Amedeo Avogadro", email = "avogadro@unito.it" }
]
license = "BSD-3-Clause"  # An SPDX license identifier, see https://spdx.org/licenses/
# These fields are optional:
readme = "README.md"
requires-python = ">=3.10"  # If you choose to specify this, please follow the Avogadro Python version policy!
# Dependencies that should be sourced from PyPI, the Python Package Index
dependencies = [
    "numpy>=2.2.6",
    "platformdirs>=4.2.0",
]


################################################################################
# Python package configuration
################################################################################
# The entry point for the plugin, that Avogadro runs
# The key is the command, which must match the plugin's name
# The entry point itself can be any function you like from within your package
[project.scripts]
avogadro-demo-pypkg = "avogadro_demo_pypkg:main"

# Some build system is always required for a package, but you are welcome to
# choose whichever you like - `uv_build` and `hatchling` are good choices
# It is recommended to specify one, but it is not required - if none is given
# then a default (`setuptools`) will be used
[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.10.2,<0.11.0"]


################################################################################
# Pixi configuration
################################################################################
# Even if your plugin has no Conda dependencies and is a standard Python package
# that doesn't require Pixi to function, you *must* include these Pixi tables!
# If you have Pixi, you can run `pixi init` to set this up for you
[tool.pixi.workspace]
channels = ["conda-forge"]
# Just specify those platforms that your plugin works on
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
# For reference, these are all the platforms that Avogadro ships for:
#platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64", "win-arm64"]

# The plugin package itself must be listed here as an editable dependency in
# order for Avogadro to be able to run your plugin
# Do NOT list any other PyPI dependencies here! Specify them under `project.dependencies`
[tool.pixi.pypi-dependencies]
avogadro-demo-pypkg = { path = ".", editable = true }

# Any Conda dependencies that your plugin needs - may be empty
[tool.pixi.dependencies]
#numpy = ">=2.2.6"

[tool.pixi.tasks]


################################################################################
# Avogadro metadata
################################################################################
[tool.avogadro]
minimum-avogadro-version = "1.103"

# Features provided by the plugin are listed in arrays of tables by feature type
# See https://toml.io/en/v1.0.0#array-of-tables

[[tool.avogadro.energy-models]]
# Each feature must specify an `identifier`, which is the first argument passed
# to the plugin when Avogadro runs it
identifier = "stellar"
model-name = "STELLAR"
input-format = "cjson"
support.gradients = false
support.elements = "1-42, 44-60, 62-94"  # Those with stable isotopes
support.unit-cell = false
support.ions = true
support.radicals = true
description = "A model that causes molecules to either explode or implode"


[[tool.avogadro.electrostatic-models]]
identifier = "avogadro_charges"  # Unlike the plugin name, feature identifiers may contain underscores
model-name = "N_A"
input-format = "sdf"
input-cjson = true  # If true, Avogadro will always pass the CJSON as well as `input-format`
support.elements = "1-86"  # up to Radon
support.charges = true
support.potentials = false

# Localization of a string is provided by replacing the simple string with a
# table containing localized strings (cf the unlocalized description above)
# The keys are the locale codes
# If *any* localized strings are provided, a default string *must* then also be
# provided under the `default` key, which is used as the fallback
[tool.avogadro.electrostatic-models.description]
default = "Assign atomic partial charges according to the digits of Avogadro's number"
de = "Partialladungen nach den Ziffern der Avogadro-Konstante zuordnen."


[[tool.avogadro.file-formats]]
identifier = "zyx"
format-name = "ZYX format"
file-extensions = [ "zyx" ]
mime-types = [ "chemical/x-zyx" ]
description = "Mostly useless file format, xyz-style files with reversed coordinates"
support.read = true
support.write = true
output-format = "xyz"
input-format = "xyz"


[[tool.avogadro.input-generators]]
identifier = "qavocado"
program-name = "Quantum Avocado"
input-format = "cjson"
support.molecular = true
support.periodic = false
# Optional paths to files (JSON or TOML) specifying:
user-options = "src/customization/qavocado_options.toml"  # options in the dialog
highlight-styles = "src/customization/qavocado_syntax.toml"  # syntax highlighting rules


[[tool.avogadro.menu-commands]]
identifier = "transmute"
input-format = "cjson"
menu = "Build"  # The menu within which the command's menu item should appear
item = "Transmute into gold"  # The text for the command's menu item
menu-priorities = [ 300 ]  # Determines the menu item's position within `menu`


# Entries with higher priority will come higher in the parent menu, so the three
# following commands will appear in an Extensions > Demo submenu in the same
# order they are listed here
[[tool.avogadro.menu-commands]]
identifier = "moveatom"
input-format = "cjson"
user-options = "src/customization/moveatom_options.json"
menu = "Extensions"
submenu = "Demo"
item = "Move Atom…"
menu-priorities = [
    500, # The priority of `submenu` ("Demo") within `menu` ("Extensions")
    210, # The priority of `item` ("Move Atom…") within `submenu` ("Demo")
]


# Here we localize the menu/item strings using in-line tables
[[tool.avogadro.menu-commands]]
identifier = "moveall"
input-format = "cjson"
menu = "Extensions"
submenu = { default = "Demo", de = "Beispiel" }
item = { default = "Move All", de = "Alle verschieben" }
menu-priorities = [ 500, 200 ]


# Here we localize the menu/item strings using a table for each string
[[tool.avogadro.menu-commands]]
identifier = "hello"
input-format = "cjson"
menu = "Extensions"
menu-priorities = [ 500, 100 ]

[tool.avogadro.menu-commands.submenu]
default = "Demo"
de = "Beispiel"

[tool.avogadro.menu-commands.item]
default = "Say Hello"
de = "Begrüßen :)"
de_CH = "Begrüssen :)"
