[project]
# These fields are required:
name = "pypkg-demo"
version = "6.0.2"
description = "An example Python package plugin for Avogadro 2 to demonstrate the revamped plugin API in v2.0 onwards"
authors = [
    { name = "Amedeo Avogadro", email = "avogadro@unito.it" }
]
license = "BSD-3-Clause"  # An SPDX license identifier, see https://spdx.org/licenses/
# These fields are optional:
readme = "README.md"
requires-python = ">=3.10"  # If you choose to specify this, please follow the Avogadro Python version policy!
dependencies = [
    "numpy>=2.2.6",
    "platformdirs>=4.2.0",
]

# Define the entry point for the plugin
# The key is the command, which must be the plugin's name, prefixed with `avogadro-`
# The entry point itself can be any function you like from within your package
[project.scripts]
avogadro-pypkg-demo = "pypkg_demo:main"

# Some build system is always required for a package, but you are welcome to
# choose whichever you like, it doesn't have to be uv_build
# It is recommended to specify one, but it is not required - if none is given
# then a default will be used
[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"


# The [tool.avogadro] table tells Avogadro what your plugin needs and what it can do
[tool.avogadro]
minimum-avogadro-version = "1.103"

# Features provided by the plugin are listed in arrays of tables, by feature type
# See https://toml.io/en/v1.0.0#array-of-tables

# Each feature must specify an `identifier`, which must be the name of the script
# that provides the feature
[[tool.avogadro.energy-models]]
identifier = "stellar"
model-name = "STELLAR"
input-format = "cjson"  # If true, Avogadro will always pass the CJSON as well as `input-format`
support.gradients = false
support.elements = "1-42, 44-60, 62-94"  # Those with stable isotopes
support.unit-cell = false
support.ions = true
support.radicals = true
description = "A model that causes molecules to either explode or implode"


[[tool.avogadro.electrostatic-models]]
identifier = "avogadro_charges"  # Unlike the plugin name, feature identifiers may contain underscores
model-name = "N_A"
input-format = "sdf"
input-cjson = true
support.elements = "1-86"  # up to Radon
support.charges = true
support.potentials = false

# Localization of a string is provided by replacing the simple string with a
# table containing localized strings (cf the unlocalized description above)
# The keys are the locale codes
# If *any* localized strings are provided, a default string *must* then also be
# provided under the `default` key, which is used as the fallback
[tool.avogadro.electrostatic-models.description]
default = "Assign atomic partial charges according to the digits of Avogadro's number"
de = "Partialladungen nach den Ziffern der Avogadro-Konstante zuordnen."


[[tool.avogadro.file-formats]]
identifier = "zyx"
format-name = "ZYX format"
file-extensions = [ "zyx" ]
mime-types = [ "chemical/x-zyx" ]
description = "Mostly useless file format, xyz-style files with reversed coordinates"
support.read = true
support.write = true
output-format = "xyz"
input-format = "xyz"


[[tool.avogadro.input-generators]]
identifier = "qavocado"
program-name = "Quantum Avocado"
input-format = "cjson"
support.molecular = true
support.periodic = false
# Optional paths to files (JSON or TOML) specifying:
user-options = "src/customization/qavocado_options.toml"  # options in the dialog
highlight-styles = "src/customization/qavocado_syntax.toml"  # syntax highlighting rules


# In these `menu-commands` examples, the flexibility of TOML is demonstrated --
# all are reasonable ways to specify the `path` data, so do whatever's easiest
# for you!

[[tool.avogadro.menu-commands]]
identifier = "transmute"
input-format = "cjson"
path.menu = "Build"  # The menu within which the command's menu item should appear
path.item.label = "Transmute into gold" # The text for the command's menu item
path.item.priority = 300 # The command item's position within "Build"


# Entries with higher priority will come higher in the parent menu, so the three
# following commands will appear in an Extensions > Demo submenu in the same
# order they are listed here
[[tool.avogadro.menu-commands]]
identifier = "moveatom"
input-format = "cjson"
user-options = "customization/moveatom_options.json"

[tool.avogadro.menu-commands.path]
menu = "Extensions"
submenu.priority = 500 # Priority determines the position of "Demo" within "Extensions"
submenu.label = "Demo"
item.priority = 210 # Priority determines the position of "Move Atom…" within "Demo"
item.label = "Move Atom…"


[[tool.avogadro.menu-commands]]
identifier = "hello"
input-format = "cjson"
path.menu = "Extensions"
path.submenu.priority = 500
path.item.priority = 100

# Here we have a table specifically for the localization of each string
[tool.avogadro.menu-commands.path.submenu.label]
default = "Demo"
de = "Beispiel"

[tool.avogadro.menu-commands.path.item.label]
default = "Say Hello"
de = "Begrüßen :)"
de_CH = "Begrüssen :)"


[[tool.avogadro.menu-commands]]
identifier = "moveall"
input-format = "cjson"

[tool.avogadro.menu-commands.path]
menu = "Extensions"
submenu.priority = 500
submenu.label = { default = "Demo", de = "Beispiel" }
item.priority = 200
item.label = { default = "Move All", de = "Alle verschieben" }
