# First, some general metadata

# These fields are required:
name = "pyscript-demo"
version = "0.1.0"
description = "An example Python script plugin for Avogadro 2 to demonstrate the revamped plugin API in v2.0 onwards"
authors = [
    { name = "Amedeo Avogadro", email = "avogadro@unito.it" }
]
license = "BSD-3-Clause"  # An SPDX license identifier, see https://spdx.org/licenses/
# These fields are optional:
readme = "README.md"

# Second, tell Avogadro what your plugin needs and what it can do

plugin-type = "pyscript"

# Configuration options that Avogadro should store on behalf of your plugin
[user-config]
hello_repeats = { type = "integer", default = 1, minimum = 1, maximum = 5 }  # See `hello.py` for how this is used

# Features provided by the plugin are listed in arrays of tables, by feature type
# See https://toml.io/en/v1.0.0#array-of-tables

# Each feature must specify an `identifier`, which must be the name of the script
# that provides the feature

#[[charges]]
# See the pypkg/pypixi demos for an example of a `charges` feature

#[[energy]]
# See the pypkg/pypixi demos for an example of an `energy` feature

[[formats]]
identifier = "zyx"
format-name = "ZYX format"
file-extensions = [ "zyx" ]
mime-types = [ "chemical/x-zyx" ]
description = "Mostly useless file format, xyz-style files with reversed coordinates"
support.read = true
support.write = true
output-format = "xyz"
input-format = "xyz"

[[generators]]
identifier = "qavocado"
program-name = "Quantum Avocado"
input-format = "cjson"
highlight-styles = "qavocado_syntax.json"  # An optional path to a file specifying syntax highlighting rules

# This syntax indicates a `user-options` subtable of the most recent `generators` table
[generators.user-options]
# Input generators should link to the available presets for common fields
title = { preset = "Title", default = "" }
calc_type = { preset = "Calculation Type", default = 1, values = [ "Single Point", "Equilibrium Geometry", "Frequencies" ] }
theory = { preset = "Theory", default = 2, values = [ "HF", "MP2", "B3LYP", "B3LYP5", "EDF1", "M062X", "CCSD" ] }
filename_base = { preset = "Filename Base", default = "job" }
charge = { preset = "Charge", default = 0, minimum = -9, maximum = 9 }
multiplicity = { preset = "Multiplicity", default = 1, minimum = 1, maximum = 6 }
# Fields that aren't presets require a type
comment = { type = "string", label = "Additional comments:", default = "" }

# If a key/value pair in user-options is particularly long, rather than writing
# it in-line it can be a good idea to put it into a proper table e.g.
[generators.user-options.basis]
preset = "Basis"
default = 2
values = [
    "STO-3G",
    "3-21G",
    "6-31G(d)",
    "6-31G(d,p)",
    "6-31+G(d)",
    "6-311G(d)",
    "cc-pVDZ",
    "cc-pVTZ",
    "LANL2DZ",
    "LACVP",
]

[[commands]]
identifier = "transmute"
input-format = "cjson"
path.menu = "Build"  # The menu within which the command's menu entry should appear
path.entry = { label = "Transmute into gold", priority = 300 }  # The text for the command's menu entry and its position within "Build"

# Entries with higher priority will come higher in the parent menu, so the three
# following commands will appear in an Extensions > Demo submenu in the same
# order they are listed here
[[commands]]
identifier = "moveatom"
input-format = "cjson"
path.menu = "Extensions"
path.submenu = { menu = "Demo", priority = 500 }  # Priority determines the position of "Demo" within "Extensions"
path.entry = { label = "Move Atom…", priority = 210 }  # Priority determines the position of "Move Atom…" within "Demo"

[commands.user-options]
selection = { type = "integer", label = "Move atom (index):", default = 0, minimum = 0 }

[[commands]]
identifier = "moveall"
input-format = "cjson"
path.menu = "Extensions"
path.submenu = { menu = "Demo", priority = 500 }
path.entry = { label = "Move All", priority = 200 }

[[commands]]
identifier = "hello"
input-format = "cjson"
path.menu = "Extensions"
path.submenu = { menu = "Demo", priority = 500 }
path.entry = { label = "Say Hello", priority = 100 }
