################################################################################
# General metadata
################################################################################
# Specified in the same way as Python package metadata would be, see
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
# These fields are required:
name = "avogadro-demo-pyscript"  # Must begin with `avogadro-` and may not include underscores
version = "6.0.2"
description = "An example Python script plugin for Avogadro 2 to demonstrate the revamped plugin API in v2.0 onwards"
authors = [
    { name = "Amedeo Avogadro", email = "avogadro@unito.it" }
]
license = "BSD-3-Clause"  # An SPDX license identifier, see https://spdx.org/licenses/
# These fields are optional:
readme = "README.md"


################################################################################
# Avogadro metadata
################################################################################
minimum-avogadro-version = "1.103"

# Features provided by the plugin are listed in arrays of tables by feature type
# See https://toml.io/en/v1.0.0#array-of-tables


#[[electrostatic-models]]
# See the pypkg demo for an example of an `electrostatic-models` feature


#[[energy-models]]
# See the pypkg demo for an example of an `energy-models` feature

[[file-formats]]
# Each feature must specify an `identifier`, which must match the name of the
# script that provides the feature - it may contain underscores
identifier = "zyx"
format-name = "ZYX format"
file-extensions = [ "zyx" ]
mime-types = [ "chemical/x-zyx" ]
description = "Mostly useless file format, xyz-style files with reversed coordinates"
support.read = true
support.write = true
output-format = "xyz"
input-format = "xyz"


[[input-generators]]
identifier = "qavocado"
program-name = "Quantum Avocado"
input-format = "cjson"
support.molecular = true
support.periodic = false
# Optional paths to files (JSON or TOML) specifying:
user-options = "src/customization/qavocado_options.toml"  # options in the dialog
highlight-styles = "src/customization/qavocado_syntax.toml"  # syntax highlighting rules


# In these `menu-commands` examples, the flexibility of TOML is demonstrated
# All are reasonable ways to specify the `path` data, so do whatever's easiest
# for you!

[[menu-commands]]
identifier = "transmute"
input-format = "cjson"
path.menu = "Build"  # The menu within which the command's menu item should appear
path.item.label = "Transmute into gold" # The text for the command's menu item
path.item.priority = 300 # The command item's position within "Build"


# Entries with higher priority will come higher in the parent menu, so the three
# following commands will appear in an Extensions > Demo submenu in the same
# order they are listed here
[[menu-commands]]
identifier = "moveatom"
input-format = "cjson"
user-options = "customization/moveatom_options.json"

[menu-commands.path]
menu = "Extensions"
submenu.priority = 500 # Priority determines the position of "Demo" within "Extensions"
submenu.label = "Demo"
item.priority = 210 # Priority determines the position of "Move Atom…" within "Demo"
item.label = "Move Atom…"


[[menu-commands]]
identifier = "moveall"
input-format = "cjson"
# Localization of a string is provided by replacing the simple string with a
# table containing localized strings
# The keys are the locale codes
# If *any* localized strings are provided, a default string *must* then also be
# provided under the `default` key, which is used as the fallback
[menu-commands.path]
menu = "Extensions"
submenu.priority = 500
submenu.label = { default = "Demo", de = "Beispiel" }
item.priority = 200
item.label = { default = "Move All", de = "Alle verschieben" }


[[menu-commands]]
identifier = "hello"
input-format = "cjson"
path.menu = "Extensions"
path.submenu.priority = 500
path.item.priority = 100

# Here we have a table specifically for the localization of each string
[menu-commands.path.submenu.label]
default = "Demo"
de = "Beispiel"

[menu-commands.path.item.label]
default = "Say Hello"
de = "Begrüßen :)"
de_CH = "Begrüssen :)"
